Repository view-design/ViewUIPlus, pull requests merged in 2025-04, with the labels that each got.

#406 fix: #361 #386
  examples/routers/message.vue
  examples/routers/notice.vue
  src/components/base/notification/index.js
Labels: size:S

#407 fix: Message销毁报错问题
  examples/routers/message.vue
  src/components/base/notification/index.js
Labels: size:XS

#408 feature: 兼容Table的fixed滚动条遮挡问题
  examples/routers/table.vue
  src/components/table/mixin.js
  src/components/table/table-body.vue
  src/components/table/table-head.vue
Labels: size:M

#405 feature: Create SECURITY.md
  SECURITY.md
Labels: size:XS
